services:
  - type: web
    name: trading-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: AUTHORIZED_USERS
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: SOLSCAN_API_KEY
        sync: false
